{
 "title": "UPF On K3s",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "UPF TX Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_network_transmit_bytes_total{\n    namespace=\"pwk-open5gs\",\n    pod=~\"open5gs-upf.*\",\n    interface=\"ogstun\"\n  }[5m])\n) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF on K3s CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"pwk-open5gs\",\n    pod=~\"open5gs-upf.*\",\n    container=\"open5gs-upf\"\n  }[5m])\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF Network RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(container_network_receive_bytes_total{\n    namespace=\"pwk-open5gs\",\n    pod=~\"open5gs-upf.*\",\n    interface=\"ogstun\"\n  }[5m])\n) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"pwk-open5gs\",pod=~\"open5gs-upf.*\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}